number5 = int(input("5--->:"))
number3 = int(input("3--->:"))
number6 = int(input("6--->:"))
print(number5 + number3 + number6)
print(number5 * number3 * number6)
print(number5 - number3 - number6)
print(number5 + number3 * number6)
print(number5 + number6 - number3)
print(number5 // number3 // number6)
print(number5 - number6 -number3)
print(number5 * number3 * number6)
print(number5 + number3 +number6)
print(number5 + number6 - number3)
print(number5 - number3 + number6)
print(number5 + number6 - number3)
print(number6 * number3 * number5)
print(number5 - number3 * number6)
print(number5 * number3 * number6)
print(number5 - number3 + number6)