E = input("me:")
print("Saba: hello")
E = input("me")
print("Saba:10")
E = input("me")
print("Saba:whats your hobby?")
E = input("me")
print("Saba:wow,i like boxing to")
E = input("me")
print("Saba:ok,see you!")